<a href="https://colab.research.google.com/github/Karpagalaksh/Cadetx_DataAnlyst_Project/blob/main/CadetX_Module1_Profiling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q kaggle

In [2]:
import pandas as pd
import os

In [3]:
os.environ['KAGLE_API_TOKEN'] = 'KGAT_8dd65e05501e92f0ea4323c419c558da'

In [4]:
# Cell 4 — dataset download
!kaggle datasets download -d adarshsng/lending-club-loan-data-csv
!unzip -q lending-club-loan-data-csv.zip -d lending_club_data2

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/adarshsng/lending-club-loan-data-csv
License(s): DbCL-1.0
Downloading lending-club-loan-data-csv.zip to /content
100% 339M/339M [00:14<00:00, 25.0MB/s]

In [5]:
!ls lending_club_data2

LCDataDictionary.xlsx  loan.csv

In [6]:
df = pd.read_csv('lending_club_data2/loan.csv')
print("shape:",df.shape)
df.head()

/tmp/ipykernel_5147/3892028724.py:1: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('lending_club_data2/loan.csv')

shape: (2260668, 145)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
print("Column Data Types")
print(df.dtypes.value_counts())
print("/n")

Column Data Types
float64    105
object      36
int64        4
Name: count, dtype: int64
/n

In [8]:
missing = df.isnull().sum()
missing_percent = (missing/len(df))*100

missing_summary = pd.DataFrame({
    "Missing":missing,
    "Missing %":missing_percent
})
missing_summary = missing_summary[missing_summary["Missing %"]>0]
missing_summary.sort_values("Missing %",ascending=False)
print("column with missing values:")
missing_summary

column with missing values:

                       Missing   Missing %
id                     2260668  100.000000
member_id              2260668  100.000000
emp_title               166969    7.385826
emp_length              146907    6.498389
annual_inc                   4    0.000177
...                        ...         ...
settlement_status      2227612   98.537777
settlement_date        2227612   98.537777
settlement_amount      2227612   98.537777
settlement_percentage  2227612   98.537777
settlement_term        2227612   98.537777

[113 rows x 2 columns]

In [9]:
df.shape

(2260668, 145)

In [10]:
dup_count = df.duplicated().sum()
dup_pct = round(dup_count/len(df)*100,2)
print("Duplicate_Rows: ", dup_count)
print("Duplicate_%: ", dup_pct)

Duplicate_Rows:  0
Duplicate_%:  0.0

In [11]:
profiling_report = {}

profiling_report["duplicates"] = {
    "full_row_duplicates": int(dup_count),
    "full_row_duplicate_pct": float(dup_pct),
    "note": "No duplicate rows found in the dataset."
}
profiling_report["duplicates"]

{'full_row_duplicates': 0,
 'full_row_duplicate_pct': 0.0,
 'note': 'No duplicate rows found in the dataset.'}