In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/loan.csv')
print("shape:",df.shape)
df.head()

shape: (21994, 145)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("Column Data Types")
print(df.dtypes.value_counts())
print("/n")

Column Data Types
float64    86
int64      34
object     25
Name: count, dtype: int64
/n

In [ ]:
missing = df.isnull().sum()
missing_percent = (missing/len(df))*100

missing_summary = pd.DataFrame({
    "Missing":missing,
    "Missing %":missing_percent
})
missing_summary = missing_summary[missing_summary["Missing %"]>0]
missing_summary.sort_values("Missing %",ascending=False)
print("column with missing values:")
missing_summary

column with missing values:

                       Missing   Missing %
id                       21994  100.000000
member_id                21994  100.000000
emp_title                 3687   16.763663
emp_length                1977    8.988815
url                      21994  100.000000
...                        ...         ...
settlement_status        21994  100.000000
settlement_date          21994  100.000000
settlement_amount        21994  100.000000
settlement_percentage    21994  100.000000
settlement_term          21994  100.000000

[83 rows x 2 columns]